services:
  - type: web
    name: Neural_Tech
    env: python
    buildCommand: |
       pip install -r requirements.txt &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput
    startCommand: "gunicorn mi_sitio.wsgi:application --timeout 60"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Neural_Tech.settings
      - key: DATABASE_URL
        value: postgresql://db_neural_2325_user:8XUKWKwTtmZCc4LPqog7LYQPxGwTv3fr@dpg-d9ejd3taeets73bas1bg-a.oregon-postgres.render.com/db_neural_2325
