services:
  - type: web
    name: Neural_Tech
    env: python
    buildCommand: |
      pip install -r requirements.txt &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput
    startCommand: "gunicorn Neural_Tech.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Neural_Tech.settings
      - key: DATABASE_URL
        value: postgresql://proyectodjango_mbzf_user:GEBvFrOkWS4YT5hd1ikWEOtmn4MjjhD9@dpg-d8u6qjkvikkc73d9b8n0-a.oregon-postgres.render.com/proyectodjango_mbzf