# Generated by Django 6.0.4 on 2026-05-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('empresa', models.CharField(max_length=200)),
                ('servicio', models.CharField(max_length=200)),
                ('mensaje', models.TextField(max_length=200)),
            ],
            options={
                'db_table': 'consultas',
            },
        ),
    ]
