# Generated by Django 6.0.4 on 2026-05-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio (USD)')),
                ('categoria', models.CharField(choices=[('software', 'Software'), ('hardware', 'Hardware'), ('servicio', 'Servicio'), ('solucion', 'Solución IA'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Categoría')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
                'ordering': ['-creado_en'],
            },
        ),
    ]
