# Generated by Django 6.0.4 on 2026-06-24 22:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0002_producto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultas',
            options={'ordering': ['-fecha_envio'], 'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
        migrations.AddField(
            model_name='consultas',
            name='categoria',
            field=models.CharField(choices=[('Consulta Comercial', 'Consulta Comercial'), ('Consulta Técnica', 'Consulta Técnica'), ('Consulta de RRHH', 'Consulta de RRHH'), ('Consulta General', 'Consulta General')], default='Consulta General', max_length=50),
        ),
        migrations.AddField(
            model_name='consultas',
            name='fecha_envio',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultas',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='consultas',
            name='empresa',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='consultas',
            name='mensaje',
            field=models.TextField(),
        ),
    ]
