# Generated by Django 6.0.4 on 2026-06-25 00:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0003_alter_consultas_options_consultas_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioPermitido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('codigo_validacion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'usuarios_permitidos',
            },
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.AlterModelOptions(
            name='consultas',
            options={'ordering': ['-fecha_envio']},
        ),
        migrations.AlterField(
            model_name='consultas',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='consultas',
            name='fecha_envio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
