# Generated by Django 6.0.4 on 2026-07-30 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0005_contenidositio'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopermitido',
            name='autorizado_admin',
            field=models.BooleanField(default=False, help_text='Tildar para que este usuario obtenga permisos de administrador al validar su cuenta.'),
        ),
    ]
